==== MCAA Sevens Head Coach  ====
May 30, 2017 +
Re: Head Coach, USA Rugby Men’s Collegiate All-Americans Sevens
(volunteer) +
United States of America Rugby Football Union, Ltd. +
2655 Crescent Drive, Unit A +
Lafayette, CO 80026 US +

Dear General Manager, Performance, +

Please accept this letter of application for the volunteer position of
Rugby Men’s Collegiate All-Americans Sevens Head Coach. I believe that
my background in rugby coaching, education, and performance analysis makes me a
unique candidate for this position, and one that would complement your
already strong team.

It seems like only yesterday that the Eagles lifted the cup trophy at
the 2015 London Sevens. That tournament showcased the
depth and diversity of the American rugby talent pipeline. Crossover
athletes, domestic club players, and experienced professionals
combined their talents to manifest that historic win. But no players
shined brighter than the rugby talent from our college ranks. Players
like Madison Hughes and Danny Barrett personify the best qualities of
rugby, with a unique American flair.

It is my belief that the United States is uniquely positioned to
achieve lasting success at the Olympics and beyond IF we capitalize on
the potential of our college rugby competitions. With
opportunities to play in both fall and spring, and an unofficial
collegiate sevens series that includes the Las Vegas Invitational,
USAR Club Sevens nationals, and the Collegiate Rugby Championship, the
American college schedule presents consistent playing opportunities
that our foreign rivals cannot match. And the college players can
continue sevens specialization through the summer by connecting with
club and select sides.

This is an opportunity that I recognized when I founded the University
of Texas rugby sevens team in 2010. At the time the only fixtures were
the LVI and the CRC. It was my belief that while UT would never
have the consistent pipeline of athletes required to consistently field
a strong fifteens program, we could develop a core group of sevens
specialists that could compete at the highest levels. Between 2010 and
2015 we were the most active college sevens program in the country,
competing in 5 LVIs, 5 CRCs, and the first 3 USAR 7s nationals. My
intuition was that by consistently exposing our core players to high
level sevens, the overall level of 15s play would also rise. This
intuition turned out to be correct as UT moved from DI-AA to DI-A to
the Varsity cup in three seasons. Of course, it is no longer a secret
that 7s is the best skills development tool for 15s players, although
the reverse is not true.

How do we unlock the potential of the United States college 7s
landscape? My vision for the program would be to use MCAA evaluation and
selection to drive consistent participation opportunities for our top collegiate
sevens athletes. Many of these opportunities would be found outside of
collegiate rugby -- pairing club and select programs with college
talent. MCAA is an individual accolade for achievement, but it also has
the potential to promote effort, investment, and alignment across the
college landscape, from competitions to individual programs. And
frankly USAR is not in a position to leave any bullets in the chamber.
Our international opponents' academy systems offer players
intense focus that we cannot match outside of a structured MCAA
evaluation and development program driven by a democratic selection
process that includes all regions and divisions.

I know I am a somewhat unknown quantity in USAR coaching circles. My
CV hits the important points so I will not rehash it here. But suffice
to say that my coaching philosophy is informed by my work as a computer
scientist. In the past few years I analyzed over 600 international
sevens matches, developing my own unique data set to mine
for rugby sevens "first principles." But as a whole my philosophy is
rests on two pillars: playing pressure defense and controlling the
match tempo. Pressure defense is the centerpiece of my sevens
philosophy. Recent series results show that it is not ball possession,
but short field scores generated by turnovers, the lead to consistent
sevens success. Who can forget the USA's heartbreaking loss to New
Zealand in the 2013 Rugby Sevens World Cup, when we turned over
the ball twice after long restarts resulting in short field tries. Series
champion South Africa are always among the lowest teams in time of
possession, yet among the highest scorers, to the extent that
generating short field scores through pressure defense should be
renamed "the South African method."

Staying behind the opponent in the penalty count is the key to controlling
tempo, because when a team receives a penalty, they can either push the
tempo by keeping the ball in play or maximize dead ball
time of possession to slow the tempo. And because most of the penalties
in sevens occur at the breakdown, cultivating the correct skills and
tactics at the contact area -- especially on defense! -- is the key to
ultimately controlling the tempo. Therefore, my coaching work focuses
on defensive organization and communication plus fundamental contact
skills. And not coincidentally I often have success with inexperienced
rugby players because these skills are decisive yet easier to acquire
than highly developed handling skills.

Thank you again for your consideration. I apologize for including so
much information. I hope we can continue the conversation as it would
be a great honor to serve along side you in this mission. Although I
am applying for the head coaching position, I would be equally happy to
serve in any coaching capacity.

Best wishes for your continued success,

Jacob Liberman +
4212 Tallowood Drive +
Austin, Texas 78731 +
+1-512-632-0098 +
jliberman@utexas.edu
