== Jacob Liberman ==
jacobliberman@gmail.com

=== Summary ===
My current work focuses on designing, developing, and validating large
scale data analysis systems based on Linux, OpenStack, and Hadoop.

Examples of my past work include:
> Developing predictive performance models for the CERN/ATLAS program
> Benchmarking 1000+ node supercomputers for the Top 500 list
> Scouting opponents at the Rugby World Cup using social network
  analysis
> Extending a mathematical model of human eye movement to include
  Smooth Pursuit

== Experience ==

*Principal Software Engineer, Cloud Computing* +
Red Hat +
January 2012 – Present +

* Develop, test, and publish cloud computing reference architectures
based on Red Hat Enterprise Linux OpenStack Platform.

*Rugby 7s Head Coach* +
University of Texas at Austin +
August 2010 – July 2015 +

* Founder and coach of University of Texas Rugby 7s team. Ranked #20
2011, #13 2012, #12 2013 out of more than 500 college rugby programs.

*Performance analyst* +
Philippine Rugby Football Union +
June 2013 – August 2013 +

* Video analyst during the 2013 Rugby 7s World Cup in Moscow, Russia.
  Video capture, coding, statistical analysis, and scouting.

*Performance Engineer, Scientific and Cloud Computing* +
Member of Technical Staff +
Advanced Micro Devices +
November 2009 – January 2012 +

* Designed and conducted performance studies for competitive analysis.
Worked directly with customers to improve performance of their codes
on our systems. Managed lab clusters for remote customer evaluation
and traveled to customer sites to conduct benchmarks for acceptance
testing.

*Development Engineer, Scientific Computing* +
Dell +
August 2006 – November 2009 +

* Lead performance engineer. Conducted performance studies using
standard benchmarks and applications. Shared results via publications
and presentations. Evaluated storage, networking, and software
technologies for inclusion in our product.

*Curriculum Designer/Subject Matter Expert* +
Dell +
February 2005 – August 2006 +

* Developed classroom and online technical curriculum for the field
  consulting team. High Performance Computing (HPC) subject matter
  expert.

*Services Consulting Engineer* +
Dell +
April 1999 – February 2005 +

* Remote and field services and support engineer. EMC storage /
  Linux / UNIX interoperability specialist.

== Education ==

*Coursera* +
Data Science Specialization

*Texas State University* +
Master's Degree +
Computer Science (incomplete)

*The University of Texas at Austin* +
Master's Degree +
Technology in Education, awarded 2006 +
4.0 GPA

*University of Wisconsin-Madison* +
Bachelor's Degree +
English Literature, awarded 1997

== Selected Publications, Example Code ==
https://github.com/jliberma?tab=repositories

== Volunteer Experience ==

*Member, Good Judgment Team* +
Good Judgment Project +
August 2014 - Present +
+
I predict global events in a government sponsored forecasting
tournament.

*Football coach / tackle specialist* +
Trojans Pop Warner +
August 2015 – Present +

I coach American football and teach rugby tackling techniques to all
age groups (5-12) to promote safe and effective tackling.

*Board member -- Rugby Network* +
Texas Exes +
May 2015 - Present +

The Texas Rugby Alumni Association is an official Texas Exes network.
We organize alumni events, promote rugby within the university, and
raise funds to offset operational costs to the University of Texas
rugby team. In 2012 we established an endowed scholarship fund through
UTIMCO.
