==== Jacob Liberman ====
jacobliberman@gmail.com +
Austin, TX

==== Summary ====
Product manager with a background in open source software, cloud computing, 
and high performance computing (HPC). Extensive experience
working with the US Federal Government and in LATAM. Multiple industry
and academic publications. Frequent presenter at technology
conferences. Ability to context switch between C-level strategic
planning and engineering-level technical discussion.

==== Experience ====

*Senior Principal Product Manager, Emerging Technology* +
Red Hat, _May 2018 - Present_ +

- Field product manager with cross organizational, cross product impact.
OpenShift and OpenStack integration. Technology evangelism through conference presentations and publications.

*Principal Product Manager, Cloud, Virtualization, Containers* +
Red Hat, _November 2016 - May 2018_ +

- Represented strategic customers to cloud business unit.
Cloud computing infrastructure design and implementation. 
Field enablement through hackfest planning and execution.

*Principal Software Engineer, Cloud Computing* +
Red Hat, _January 2012 – November 2016_ +

- Developed, tested, and published cloud computing
reference architectures based on Red Hat OpenStack Platform,
Enterprise Linux, and Hadoop.

*Rugby 7s Head Coach* +
University of Texas at Austin, _August 2010 – July 2015_ +

- Founder and coach of University of Texas Rugby 7s team. Ranked #20
2011, #13 2012, #12 2013 out of more than 500 college rugby programs.

*Performance analyst* +
Philippine Rugby Football Union, _June 2013 – August 2013_ +

- National team performance analyst during the 2013 Rugby 7s World Cup
in Moscow, Russia. Video capture, coding, statistical analysis, and
scouting.

*Performance Engineer, Scientific and Cloud Computing* +
Advanced Micro Devices, _November 2009 – January 2012_ +

- Designed and conducted server performance studies for competitive
analysis. Helped customers improve the performance of their codes
on our systems. Managed lab clusters for remote customer evaluation.
Traveled to customer sites to conduct benchmarks for acceptance
testing.

*Development Engineer, High Performance Computing* +
Dell, _August 2006 – November 2009_ +

- Lead performance engineer. Conducted server performance studies using
standard benchmarks and applications. Shared results via publications
and presentations. Evaluated storage, networking, and software
technologies for inclusion in our product.

*Curriculum Designer/Subject Matter Expert* +
Dell, _February 2005 – August 2006_ +

- Developed classroom and online technical curriculum for the field
consulting team. High Performance Computing (HPC) subject matter expert.

*Services Consulting Engineer* +
Dell, _April 1999 – February 2005_ +

- Remote field services and support engineer. I helped customers deploy
EMC storage arrays and attach UNIX and Linux servers to them.

==== Education ====

*Texas State University* +
_Master's Program_, Computer Science +
- In progress, 30 hours upper division coursework  +
- Researching CUDA acceleration for computational model of human eye movement, 

*The University of Texas at Austin* +
_Master's Degree_, Technology in Education +
- 4.0 GPA with course work in learning theory, statistics, and scientific computing.

*University of Wisconsin-Madison* +
_Bachelor's Degree_, English Literature +
- Creative writing emphasis

==== Volunteer Service ====

*Board member* +
Trojans Pop Warner, _August 2015 – 2017_ +

Web services and American football tackle saftey coach. 

*Board Member -- Texas Rugby Alumni Network* +
Texas Exes, _May 2015 - Present_ +

Organize alumni events, recruit members, and manage an
endowed scholarship fund.

==== Awards ====

- Red Hat Portfolio Marketing Customer Impact Award, 2018
- Red Hat Summit Best presenter award, 2017
- Red Hat Summit Best presenter award, 2016

==== Selected Publications, Example Code ====
https://github.com/jliberma?tab=repositories[https://github.com/jliberma]
